commercelayer:
  site: https://wishkart.commercelayer.io
  client_id: UzHVt770fWsxBGCuuJnjN_O2ijZ70QzGCGA0_mZj3Ik
  client_secret: 2ATTMcVoElj4-dCug6_aDnK3r5YPQH60aXAUFZZTMo8
contentful:
  space: xh1e4ab263r2
  access_token: c4bNFqtDwVb0GPAs4a1diBeIT99lAJeaap7FG87gtwM
